### PR TITLE
Remove dist and uglification config

### PR DESCRIPTION
**Pull request by alshakero**
And add Travis badge.

To comply with https://github.com/Palindrom/JSON-Patch-OT/issues/5#issuecomment-285670232

### CODE REVIEW

**Comment by warpech** [comment]
I don't know what the commit `2.0.0` is doing in this branch, but anyway the PR looks GTM :)

**Comment by alshakero** [comment]
@warpech now that I think about it, this is a non-breaking change, and we didn't change the name. Should I bump to 1.0.2 instead of 2.0.0? I did this because we agreed to bump major to all repo name changes. But this one's name didn't change. 

Would appreciate your advice.

**Comment by warpech** [comment]
Sorry, I have missed the question. Seems that you have already decided 12 days ago: https://github.com/Palindrom/JSON-Patch-OT/releases/tag/2.0.0

**Comment by alshakero** [comment]
@warpech no issue at all. I released because I initially thought it's the same situation is [this](https://github.com/Palindrom/JSON-Patch-Queue/pull/4#issuecomment-285394295).

**Pull request merged**
